// Generated by https://quicktype.io

import { AxiosError } from "axios";
import { tesloApi } from "../api/tesloApi";

export interface ILoginResponse {
  id: string;
  email: string;
  fullName: string;
  isActive: boolean;
  roles: string[];
  token: string;
}

export class AuthServices {
  static login = async (
    email: string,
    password: string
  ): Promise<ILoginResponse> => {
    try {
      const { data } = await tesloApi.post<ILoginResponse>("/auth/login", {
        email,
        password,
      });
      //console.log(data);
      return data;
    } catch (error) {
      if (error instanceof AxiosError) {
        //console.log(error.response?.data);
        throw new Error(error.response?.data);
      }
      console.log(error);
      throw new Error("Unable to Login");
    }
  };

  static checkStatus = async (): Promise<ILoginResponse> => {
    try {
      const { data } = await tesloApi.get("/auth/check-status");
      return data;
    } catch (error) {
      console.log(error);

      throw new Error("Unathorized");
    }
  };
}
